# Generated by Django 3.2.3 on 2021-06-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('LogId', models.AutoField(primary_key=True, serialize=False)),
                ('LOG_PRODUCER', models.CharField(max_length=100)),
                ('TIMESTAMP', models.DateField()),
                ('SEVERITY', models.IntegerField()),
                ('LOG_MESSAGE', models.CharField(max_length=100)),
            ],
        ),
    ]
