# Generated by Django 3.2.3 on 2021-06-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='LOG_MESSAGE',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='logs',
            name='TIMESTAMP',
            field=models.DateTimeField(),
        ),
    ]
